apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-service-demo
  title: Шаблон React-сервиса
  description: Быстрый старт нового React-сервиса по корпоративному стандарту.
spec:
  owner: frontend-team
  type: service

  parameters:
    - title: Основная информация
      required:
        - name
        - description
      properties:
        name:
          title: Название сервиса
          type: string
          description: Уникальное имя для создаваемого сервиса (например, my-react-app)
        description:
          title: Описание сервиса
          type: string
          description: Краткое описание создаваемого сервиса
        repoUrl:
          title: Ссылка на репозиторий (GitHub)
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Скачать шаблон
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}

    - id: publish
      name: Опубликовать в GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        protectDefaultBranch: true
        repoVisibility: public
        allowedHosts: ['github.com']

    - id: register
      name: Зарегистрировать в Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Перейти в репозиторий
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Открыть сервис в Backstage
        icon: catalog
        url: ${{ steps['register'].output.entityRef | backstageUrl }}
