---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-devops
  description: Команда DevOps
spec:
  type: team
  profile:
    displayName: DevOps Team
    email: devops@example.com
  members: [jdoe, asmith]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
spec:
  profile:
    displayName: Jenny Doe
    email: jenny.doe@example.com
  memberOf: [team-devops]
